import { useEffect, useMemo, useRef, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { TeacherBgmController } from '../audio/AudioManager';
import { TeacherCollector, type CollectorStatus, type SubmittedRecord } from '../network/teacherCollector';
import { gameTypeLabel, difficultyLabel } from '../game/tileGenerator';

const code4=()=>String(Math.floor(1000+Math.random()*9000));
const loadTeacherCode=()=>{const saved=sessionStorage.getItem('bw_teacher_code');return saved&&/^\d{4}$/.test(saved)?saved:code4()};
const loadSubmissions=():SubmittedRecord[]=>{try{return JSON.parse(sessionStorage.getItem('bw_teacher_submissions')||'[]')}catch{return[]}};
const fmt=(sec:number)=>`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;

export function TeacherPortal({onBack}:{onBack:()=>void}){
 const collector=useRef(new TeacherCollector()); const bgm=useMemo(()=>new TeacherBgmController(),[]);
 const [teacherCode]=useState(loadTeacherCode); const [collectorStatus,setCollectorStatus]=useState<CollectorStatus>('idle');
 const [submissions,setSubmissions]=useState<SubmittedRecord[]>(loadSubmissions); const [minutes,setMinutes]=useState(20); const [seconds,setSeconds]=useState(1200); const [timerRunning,setTimerRunning]=useState(false);const [timerStarted,setTimerStarted]=useState(false);
 const [bgmPlaying,setBgmPlaying]=useState(false); const [volume,setVolume]=useState(.45); const [showIntro,setShowIntro]=useState(true); const [notice,setNotice]=useState('');const [endOpen,setEndOpen]=useState(false);const [qrOpen,setQrOpen]=useState(false);
 const studentUrl=`${location.origin}${location.pathname}#student`;
 useEffect(()=>()=>bgm.pause(),[bgm]); useEffect(()=>{sessionStorage.setItem('bw_teacher_code',teacherCode)},[teacherCode]); useEffect(()=>{sessionStorage.setItem('bw_teacher_submissions',JSON.stringify(submissions))},[submissions]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),2200);return()=>clearTimeout(id)},[notice]);
 useEffect(()=>{const c=collector.current;c.onStatus=setCollectorStatus;c.onSubmission=incoming=>setSubmissions(prev=>{const idx=prev.findIndex(v=>v.profileId===incoming.profileId);if(idx<0)return [...prev,incoming];const copy=[...prev];copy[idx]=incoming;return copy});c.start(teacherCode);return()=>c.close()},[teacherCode]);
 useEffect(()=>{if(!timerRunning)return;const id=setInterval(()=>setSeconds(s=>{if(s<=1){setTimerRunning(false);return 0}return s-1}),1000);return()=>clearInterval(id)},[timerRunning]);
 const startTimer=()=>{if(!timerStarted){setSeconds(Math.max(1,minutes)*60);setTimerStarted(true);setTimerRunning(true);return;}setTimerRunning(v=>!v)};
 const resetTimer=()=>{setTimerRunning(false);setTimerStarted(false);setSeconds(Math.max(1,minutes)*60)};
 const enterOperation=async()=>{setShowIntro(false);try{await bgm.play();setBgmPlaying(true)}catch{setBgmPlaying(false)}};
 const toggleBgm=async()=>{if(bgmPlaying){bgm.pause();setBgmPlaying(false)}else{try{await bgm.play();setBgmPlaying(true)}catch{setBgmPlaying(false)}}};
 const copyStudentLink=async()=>{await navigator.clipboard?.writeText(studentUrl);setNotice('학생 페이지 링크를 복사했습니다.')};
 const sorted=()=>[...submissions].sort((a,b)=>b.record.points-a.record.points||b.record.wins-a.record.wins||(b.record.draws||0)-(a.record.draws||0));
 const copyResults=async()=>{const rows=[['순위','이름','승점','승','무','패','총경기','대결기록','제출시각']];sorted().forEach((s,i)=>rows.push([String(i+1),s.playerName,String(s.record.points),String(s.record.wins),String(s.record.draws||0),String(s.record.losses),String(s.record.games),s.record.matches.map(m=>`${m.opponentName} ${m.result} ${gameTypeLabel(m.gameType??'BASIC')} ${m.gameType==='BASIC'?'난이도 없음':difficultyLabel(m.difficulty??'EASY')}`).join(' / '),new Date(s.submittedAt).toLocaleString('ko-KR')]));await navigator.clipboard?.writeText(rows.map(r=>r.join('\t')).join('\n'));setNotice('학생 전적 결과를 복사했습니다.')};
 const endTeacherGame=()=>{bgm.pause();collector.current.close();sessionStorage.removeItem('bw_teacher_code');sessionStorage.removeItem('bw_teacher_submissions');setSubmissions([]);setTimerRunning(false);onBack()};
 if(showIntro)return <main className="teacher-intro scene-lobby"><div className="lesson-slide teacher-entry-slide intro-single"><span className="eyebrow">CLASS INTRO</span><h2>수의 크기를 비교하며 추리해요</h2><p className="intro-body">「백과 흑」에서는 타일에 적힌 값을 서로 비교하며 더 큰 값을 판단합니다. 표현이 다른 수와 길이도 비교하고, 그 결과를 이용해 상대의 타일을 추리해 봅니다.</p><div className="intro-mode-diagram"><span>기본 숫자</span><i>→</i><span>분수</span><i>→</i><span>소수</span><i>→</i><span>단위</span><i>→</i><span>분수+소수</span></div><strong className="intro-callout">다양한 유형의 숫자를 백과 흑 게임을 통해 비교해 보세요.</strong><div className="slide-nav"><button className="primary" onClick={()=>void enterOperation()}>게임 운영 시작</button></div></div></main>;
 return <main className="teacher-page scene-lobby">
  <header className="teacher-header"><div><span className="eyebrow">TEACHER CONTROL</span><h1>교사 게임 운영</h1></div><div className="teacher-header-actions"><div className={`collector-pill ${collectorStatus}`}>● {collectorStatus==='open'?'전적 수신 대기 중':'집계 연결 준비 중'}</div><button className="teacher-end-btn" onClick={()=>setEndOpen(true)}>게임 종료(전적 초기화)</button></div></header>
  <section className="teacher-grid teacher-grid-v6">
   <article className="teacher-card access-card"><div className="card-title"><b>학생 접속</b><span>학생용 페이지를 바로 열 수 있습니다.</span></div><div className="student-access"><button className="qr qr-zoom-trigger" onClick={()=>setQrOpen(true)} aria-label="학생 접속 QR 확대"><QRCodeSVG value={studentUrl} size={150}/><small>클릭하여 확대</small></button><div><label>학생 페이지 링크</label><div className="copy-line"><input readOnly value={studentUrl}/><button onClick={()=>void copyStudentLink()}>복사</button></div><small>학생들은 QR 또는 링크로 접속해 게임을 시작합니다.</small></div></div></article>
   <article className="teacher-card timer-card timer-card-large"><div className="card-title"><b>수업 타이머</b><span>시간 종료 후 학생들에게 전적 제출을 안내하세요.</span></div>{!timerStarted?<div className="timer-input-stage"><div className="timer-stepper"><input className="timer-big-input" inputMode="numeric" value={minutes} onChange={e=>setMinutes(Math.max(1,Math.min(90,Number(e.target.value.replace(/\D/g,''))||1)))}/><div className="timer-arrows"><button aria-label="1분 증가" onClick={()=>setMinutes(v=>Math.min(90,v+1))}>▲</button><button aria-label="1분 감소" onClick={()=>setMinutes(v=>Math.max(1,v-1))}>▼</button></div></div><b>분</b></div>:<div className={`timer-display ${seconds===0?'done':''}`}>{fmt(seconds)}</div>}<div className="timer-row timer-buttons"><button className="primary" onClick={startTimer}>{timerStarted?(timerRunning?'일시정지':'계속'):'시작'}</button><button className="secondary" onClick={resetTimer}>초기화</button></div></article>
  </section>
  <section className="teacher-results teacher-card"><div className="results-head"><div><span className="eyebrow">CLASS RESULT</span><h2>학생 전적 집계</h2><p>게임 종료 후 학생이 자신의 기기에서 전적을 제출하면 자동으로 갱신됩니다.</p></div><div className="teacher-code-area"><div className="teacher-code-box"><small>교사 코드</small><strong>{teacherCode}</strong></div><button className="copy-results-btn" onClick={()=>void copyResults()}>학생 전적 결과 복사하기</button><small>한셀/엑셀에 붙여넣기 하시면 학생 전적을 저장하실 수 있습니다.</small></div></div>
   <div className="result-stats"><span>제출 <b>{submissions.length}명</b></span><span>총 경기 기록 <b>{submissions.reduce((a,s)=>a+s.record.games,0)}</b></span><span>총 승점 <b>{submissions.reduce((a,s)=>a+s.record.points,0)}</b></span></div>
   {submissions.length===0?<div className="empty-submit">아직 제출된 전적이 없습니다.<br/><small>학생 페이지 → 전적 제출 → 교사 코드 {teacherCode}</small></div>:<div className="teacher-table-wrap"><table className="teacher-table"><thead><tr><th>순위</th><th>이름</th><th>승점</th><th>전적</th><th>대결 기록</th><th>제출 시각</th></tr></thead><tbody>{sorted().map((s,i)=><tr key={s.profileId}><td>{i+1}</td><td><b>{s.playerName}</b></td><td><strong>{s.record.points}</strong></td><td>{s.record.games}경기 · {s.record.wins}승 {s.record.draws||0}무 {s.record.losses}패</td><td className="opponent-list">{s.record.matches.length?s.record.matches.map((m,j)=><span key={`${m.matchId}-${j}`}>{m.opponentName} <b className={m.result.toLowerCase()}>{m.result==='WIN'?'승':m.result==='DRAW'?'무':'패'}</b> <small>{gameTypeLabel(m.gameType??'BASIC')} · {m.gameType==='BASIC'?'난이도 없음':difficultyLabel(m.difficulty??'EASY')}</small></span>):'기록 없음'}</td><td>{new Date(s.submittedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</td></tr>)}</tbody></table></div>}
  </section>
  <div className="bgm-mini"><button onClick={()=>void toggleBgm()}>{bgmPlaying?'Ⅱ':'▶'}</button><b>BGM</b><input aria-label="BGM 음량" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);bgm.setVolume(v)}}/></div>
  {qrOpen&&<div className="modal-back" onClick={()=>setQrOpen(false)}><div className="modal qr-enlarge-modal" onClick={e=>e.stopPropagation()}><h2>학생 접속 QR</h2><div className="qr-large"><QRCodeSVG value={studentUrl} size={360}/></div><p>학생 태블릿에서 QR을 스캔해 접속하세요.</p><button className="secondary" onClick={()=>setQrOpen(false)}>닫기</button></div></div>}
  {endOpen&&<div className="modal-back"><div className="modal game-confirm-modal"><span className="eyebrow">END CLASS</span><h2>게임을 종료하시겠습니까?</h2><p>전적이 초기화됩니다. 게임을 종료하고 다시 시작하시겠습니까?</p><div className="modal-actions"><button className="secondary" onClick={()=>setEndOpen(false)}>취소</button><button className="danger" onClick={endTeacherGame}>게임 종료 및 초기화</button></div></div></div>}
  {notice&&<div className="toast top-toast">{notice}</div>}
 </main>;
}
